- Makefile
- docs/guides/linux_cross_compile.md
- docs/guides/mac_cross_compile.md
Linux guide on cross-compilation.
Improvement of portability of cross-compilation, mac, linux.
Improve Makefile to prevent future modification time errors after `make clean`.
> Lib cross compile

- Makefile
- src/Source.files
- src/data/data.hpp
- src/data/placeholder.hpp
- src/state_machine/hyped-machine.cpp
- src/state_machine/hyped-machine.hpp
- src/state_machine/main.cpp
- src/state_machine/main.hpp
- src/state_machine/states.cpp
- src/state_machine/states.hpp
> Stm fix module status

- src/propulsion/can/can_sender.cpp
- src/propulsion/can/can_sender.hpp
- src/propulsion/can/fake_can_sender.cpp
- src/propulsion/can/fake_can_sender.hpp
- src/propulsion/can/sender_interface.hpp
- src/propulsion/main.cpp
- src/propulsion/main.hpp
- src/propulsion/state_processor.cpp
- src/propulsion/state_processor.hpp
- src/propulsion/state_processor_interface.hpp
Improved the general code of the can_sender and included comments for the functions.
Furthermore this branch introduced the state machines states to the main loop
> Mot add can ids

- src/propulsion/can/can_sender.cpp
- src/propulsion/can/can_sender.hpp
- src/propulsion/can/fake_can_sender.cpp
- src/propulsion/can/fake_can_sender.hpp
- src/propulsion/can/sender_interface.hpp
- src/propulsion/main.cpp
- src/propulsion/main.hpp
- src/propulsion/state_processor.cpp
- src/propulsion/state_processor.hpp
- src/propulsion/state_processor_interface.hpp
The long awaited update on the motor control code to fix lint errors
> Fix lint errors

- src/data/data.hpp
- src/state_machine/event.hpp
- src/state_machine/hyped-machine.hpp
- src/state_machine/main.cpp
- src/state_machine/main.hpp
- src/state_machine/states.hpp
should look good for both Stm and data.
> fixed linter problems for state_machine and data linter

- src/state_machine/event.hpp
- src/state_machine/hyped-machine.cpp
- src/state_machine/main.cpp
- src/state_machine/main.hpp
- src/state_machine/states.cpp
Added a new event called kReset, which requires manual interaction, to transition from the states Finished and FailureStopped.
> Stm add reset transitions

- docs/guides/connecting_rockets.md
Will add stuff on beaglebone network setup etc. soon in later PR
> Added guide on how to connect Rockets together

- src/demo_prop.cpp
- src/propulsion/main.cpp
- src/propulsion/state_processor.cpp
- src/propulsion/state_processor.hpp
- src/propulsion/state_processor_interface.hpp
The fake controller has been merged with the state processor and the state processor calls the corresponding controller functions now.
> Mot integrate fake controller

- src/telemetry/client.cpp
- src/telemetry/client.hpp
- src/telemetry/main.cpp
- src/telemetry/main.hpp
Just renamed some things and small formatting changes
> Tlm adhere to style guide

- src/Source.files
- src/demo_telem.cpp
- src/telemetry/client.cpp
- src/telemetry/client.hpp
- src/telemetry/main.cpp
- src/telemetry/main.hpp
- src/telemetry/message.proto
- src/telemetry/types/message.pb.cpp
- src/telemetry/types/message.pb.h
Definitely need to clean up and refactor in future commits, but telemetry system now (semi) integrated with shared data structure. Not as fully fleshed as I wanted to be by April 6th deadline, will continue working asap.
Also please merge this PR and not squash or rebase, would really appreciate it (makes going through history and understanding context easier at least in my opinion).
> Tlm shared data structure integration

- src/propulsion/main.cpp
fixed indentation style of main.cpp
> fix style of main

- setup.sh
Add setup script which updates and initialises git submodules
> add setup script

- src/propulsion/calculate_RPM.cpp
- src/propulsion/calculate_RPM.hpp
- src/propulsion/can/can_sender.cpp
- src/propulsion/can/can_sender.hpp
- src/propulsion/can/fake_can_sender.cpp
- src/propulsion/can/fake_can_sender.hpp
- src/propulsion/can/sender_interface.hpp
- src/propulsion/controller_interface.hpp
- src/propulsion/fake_controller.cpp
- src/propulsion/fake_controller.hpp
- src/propulsion/main.cpp
- src/propulsion/main.hpp
fixed style of fake_can_sender and can_sender
> Mot fix style

- src/Source.files
- src/demo_telem.cpp
- src/telemetry/client.cpp
- src/telemetry/client.hpp
- src/telemetry/main.cpp
- src/telemetry/main.hpp
- src/telemetry/message.proto
- src/telemetry/recvloop.cpp
- src/telemetry/recvloop.hpp
- src/telemetry/sendloop.cpp
- src/telemetry/sendloop.hpp
- src/telemetry/telemetrydata/message.pb.cpp
- src/telemetry/telemetrydata/message.pb.h
- src/telemetry/utils.cpp
- src/telemetry/utils.hpp
Fully fleshed out client side data integration. Pls don't squash, thank you!
> Tlm updated shared data structure integration

- src/demo_navigation.cpp
- src/sensors/fake_imu.cpp
- src/sensors/fake_imu.hpp
Add support for calibration for fake IMUs in which stationarity is assumed
--> output is (0, 0, 9.8) + noise
> add calibrating state for fake IMUs

- src/demo_fake_navigation.cpp
demo for navigation to use with fake IMUs to simulate entire tube run with calibration, acceleration and nominal breaking
> new navigation demo to use with fake sensors

- src/Source.files
- src/demo_log_navigation.cpp
- src/navigation/imu_data_logger.cpp
- src/navigation/imu_data_logger.hpp
- src/navigation/main_log.cpp
- src/navigation/main_log.hpp
add new logger demo to log and store measurements from multiple IMUs in CSV format
> new logger for multiple IMUs

- src/data/data.hpp
- src/demo_telem.cpp
- src/telemetry/message.proto
- src/telemetry/recvloop.cpp
- src/telemetry/telemetrydata/message.pb.cpp
- src/telemetry/telemetrydata/message.pb.h
Represents 'calibrate' command that will be sent from GUI to transition pod from Idle state to Calibrating state.
> Tlm added 'calibrate_command' to data.hpp

- src/Source.files
- src/telemetry/client.cpp
- src/telemetry/client.hpp
- src/telemetry/main.cpp
- src/telemetry/main.hpp
- src/telemetry/recvloop.cpp
- src/telemetry/recvloop.hpp
- src/telemetry/sendloop.cpp
- src/telemetry/sendloop.hpp
- src/telemetry/signalhandler.cpp
- src/telemetry/signalhandler.hpp
Some fixes before functional test.
> Tlm merge handle sigpipe and disconnect

- src/propulsion/main.cpp
Reduce Motor console output by changing the motor state logger messages to debug level 1.
> Make motors less verbose

- src/demo_fake_navigation.cpp
- src/demo_navigation.cpp
- src/navigation/main.cpp
- src/navigation/main.hpp
- src/navigation/navigation.cpp
- src/navigation/navigation.hpp
navigation module has calibration check, waits for respective states calibrating and accelerating + updated navigation demos are updated accordingly
> navigation module respects system states

- src/Source.files
- src/sensors/fake_temperature.cpp
- src/sensors/fake_temperature.hpp
- src/sensors/interface.hpp
- src/sensors/main.cpp
- src/sensors/main.hpp
- src/sensors/temperature.cpp
- src/sensors/temperature.hpp
- src/utils/system.cpp
- src/utils/system.hpp
implemented in sensors main, needed to add TemperatureInterface to ease implementation in main
> fake temp implementation

- src/sensors/bms_manager.cpp
- src/sensors/bms_manager.hpp
Safe to approach LED scheme for batteries
> Sns bms leds
